version: '{build}'
skip_tags: true

install:
    - cinst jdk10 -params 'installdir=C:\\jdk10'

build_script:
    - gradlew.bat assemble

test_script:
    - gradlew.bat check

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
        - JAVA_HOME: C:\jdk10

cache:
    - C:\Users\appveyor\.gradle\caches -> .gradle-wrapper\gradle-wrapper.properties
    - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties
    - C:\Users\appveyor\.m2\wrapper -> .mvn\wrapper\maven-wrapper.properties
    - cnf\cache\stable
    - maven\target\m2

matrix:
    fast_finish: true
